#!/usr/bin/env php
<?php

use MVC\Framework\Console\Runner;

require './core/init.php';

require ROOT_DIR . '/vendor/autoload.php';

if (php_sapi_name() == 'cli') {
    (new Runner())->run($argv);
} else {
    die("Command should run in console");
}